title: Jim Autos Thailand, Australia, UK, Dubai, USA
author: Jack
email: jim12cars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jim Autos Thailand is Thailand Car Exporter and Thailadn Car Dealer, Jim Autos Thailand is Thailand Car Exporter and Thailadn Car Dealer, 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
