title: Jim Autos Thailand
author: John
email: jim12cars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jim Autos Thailand is Thailand top car exporter and Thailand top car dealer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
